// Super Smash Bros. Ultimate roster — Miis removed, echo fighters merged
// into their base character. 76 characters -> 76 x 76 = 5776 matchups.
const CHARACTERS = [
  { slug: "mario", name: "Mario" },
  { slug: "donkey_kong", name: "Donkey Kong" },
  { slug: "link", name: "Link" },
  { slug: "samus", name: "Samus / Dark Samus" },
  { slug: "yoshi", name: "Yoshi" },
  { slug: "kirby", name: "Kirby" },
  { slug: "fox", name: "Fox" },
  { slug: "pikachu", name: "Pikachu" },
  { slug: "luigi", name: "Luigi" },
  { slug: "ness", name: "Ness" },
  { slug: "captain_falcon", name: "Captain Falcon" },
  { slug: "jigglypuff", name: "Jigglypuff" },
  { slug: "peach", name: "Peach / Daisy" },
  { slug: "bowser", name: "Bowser" },
  { slug: "ice_climbers", name: "Ice Climbers" },
  { slug: "sheik", name: "Sheik" },
  { slug: "zelda", name: "Zelda" },
  { slug: "dr_mario", name: "Dr. Mario" },
  { slug: "pichu", name: "Pichu" },
  { slug: "falco", name: "Falco" },
  { slug: "marth", name: "Marth / Lucina" },
  { slug: "young_link", name: "Young Link" },
  { slug: "ganondorf", name: "Ganondorf" },
  { slug: "mewtwo", name: "Mewtwo" },
  { slug: "roy", name: "Roy / Chrom" },
  { slug: "mr_game_and_watch", name: "Mr. Game & Watch" },
  { slug: "meta_knight", name: "Meta Knight" },
  { slug: "pit", name: "Pit / Dark Pit" },
  { slug: "zero_suit_samus", name: "Zero Suit Samus" },
  { slug: "wario", name: "Wario" },
  { slug: "snake", name: "Snake" },
  { slug: "ike", name: "Ike" },
  { slug: "pokemon_trainer", name: "Pokémon Trainer" },
  { slug: "diddy_kong", name: "Diddy Kong" },
  { slug: "lucas", name: "Lucas" },
  { slug: "sonic", name: "Sonic" },
  { slug: "king_dedede", name: "King Dedede" },
  { slug: "olimar", name: "Olimar" },
  { slug: "lucario", name: "Lucario" },
  { slug: "rob", name: "R.O.B." },
  { slug: "toon_link", name: "Toon Link" },
  { slug: "wolf", name: "Wolf" },
  { slug: "villager", name: "Villager" },
  { slug: "mega_man", name: "Mega Man" },
  { slug: "wii_fit_trainer", name: "Wii Fit Trainer" },
  { slug: "rosalina_and_luma", name: "Rosalina & Luma" },
  { slug: "little_mac", name: "Little Mac" },
  { slug: "greninja", name: "Greninja" },
  { slug: "palutena", name: "Palutena" },
  { slug: "pac_man", name: "Pac-Man" },
  { slug: "robin", name: "Robin" },
  { slug: "shulk", name: "Shulk" },
  { slug: "bowser_jr", name: "Bowser Jr." },
  { slug: "duck_hunt", name: "Duck Hunt" },
  { slug: "ryu", name: "Ryu / Ken" },
  { slug: "cloud", name: "Cloud" },
  { slug: "corrin", name: "Corrin" },
  { slug: "bayonetta", name: "Bayonetta" },
  { slug: "inkling", name: "Inkling" },
  { slug: "ridley", name: "Ridley" },
  { slug: "simon", name: "Simon / Richter" },
  { slug: "king_k_rool", name: "King K. Rool" },
  { slug: "isabelle", name: "Isabelle" },
  { slug: "incineroar", name: "Incineroar" },
  { slug: "piranha_plant", name: "Piranha Plant" },
  { slug: "joker", name: "Joker" },
  { slug: "hero", name: "Hero" },
  { slug: "banjo_and_kazooie", name: "Banjo & Kazooie" },
  { slug: "terry", name: "Terry" },
  { slug: "byleth", name: "Byleth" },
  { slug: "minmin", name: "Min Min" },
  { slug: "steve", name: "Steve" },
  { slug: "sephiroth", name: "Sephiroth" },
  { slug: "pyra", name: "Pyra & Mythra" },
  { slug: "kazuya", name: "Kazuya" },
  { slug: "sora", name: "Sora" },
];

const N = CHARACTERS.length; // 76
const TOTAL_MATCHUPS = N * N; // 5776
